server:
  port: 80
  servlet:
    context-path: /api

spring:
  application:
    name: xht-cloud-service-generate
  main:
    allow-circular-references: true #解决循环依赖问题
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher # swagger 冲突解决
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  profiles:
    active: @profiles.active@
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/xht-cloud-generate?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    #Druid连接池配置
    initial-size: 5 #初始化时建立物理连接的个数
    max-active: 30 #最大连接池数量
    min-idle: 5 # 最小连接池数量
    druid.max-wait: 60000 #获取连接时最大等待时间，单位毫秒
    time-between-eviction-runs-millis: 60000 #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    min-evictable-idle-time-millis: 300000 #连接保持空闲而不被驱逐的最小时间
    validation-query: select 'x' #用来检测连接是否有效的sql 必须是一个查询语句：mysql中为 select 'x' oracle中为 select 1 from dual
    test-while-idle: true #建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
    test-on-borrow: false #申请连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
    test-on-return: false #归还连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
    pool-prepared-statements: true #是否缓存preparedStatement,mysql5.5+建议开启
    max-pool-prepared-statement-per-connection-size: 50 #要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。
    filters: stat,wall #配置监控统计拦截的filters，去掉后监控界面sql无法统计
    connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500 #通过connectProperties属性来打开mergeSql功能；慢SQL记录
    use-global-data-source-stat: true #合并多个DruidDataSource的监控数据
    #StatViewServlet配置
    stat-view-servlet.enabled: true #是否启用StatViewServlet（监控页面）默认值为false
    stat-view-servlet.login-username: admin #设置访问druid监控页的账号,默认没有
    stat-view-servlet.login-password: admin #设置访问druid监控页的密码,默认没有

mybatis-plus:
  global-config:
    db-config:
      id-type: assign_uuid
      logic-delete-field: delFlag  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
    banner: false
  mapper-locations: classpath*:/mapper/*.xml  #加载mybatis的配置文件

# swagger配置
swagger:
  title: 代码生成器接口文档
  basePackage: com.xht.cloud.service.generate.controller
  license: xht
  licenseUrl: xht
  contactName: 小糊涂
  contactUrl: www.我没有地址.com
  contactEmail: 616326125@.com
  version: ${xht-cloud-version}
